name: SSH Commands on ContainerPorts-2

on:
  push:
    branches:
      - main

jobs:
  ssh-on-container-ports:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Extract and SSH on ContainerPorts
      run: |
        containerPorts=($(awk '/containerPort:/' pod.yaml))
        echo "$containerPorts"
