name: SSH Commands on ContainerPorts

on:
  push:
    branches:
      - main

jobs:
  ssh-on-container-ports:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Extract and SSH on ContainerPorts
      run: |
        # Loop over each containerPort in pod.yaml
        cat pod.yaml
        cat pod.yaml | jq -r '.spec.containers[].ports[].containerPort' | while read -r containerPort; do
          # Print the current containerPort
          echo "Container Port: $containerPort"

          # SSH command using the current containerPort
          # ssh user@host "your_command_using_$containerPort"
        done
